version: '3.4'

services:
  conferenceattendees.api:
    image: ${DOCKER_REGISTRY-}conferenceattendeesapi
    build:
      context: .
      dockerfile: ConferenceAttendees.Api/Dockerfile
    ports:
       - "7106:7106"
    environment:
       - ASPNETCORE_URLS=http://*:7106
    depends_on: [mssql,seq_logs]
    networks:
        - app-network

  mssql:
    image: "pysachindocker/conferenceattendeedb"
    container_name: sql2
    hostname: mssql
    restart: unless-stopped
    ports:
        - "1401:1433"
    networks:
        - app-network

  seq_logs:
    image: datalust/seq
    restart: unless-stopped
    ports:
        - "5342:80"
    environment:
        - ACCEPT_EULA=Y
    networks:
        - app-network
  nginx:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8083:8083"
    depends_on:
        - conferenceattendees.api
    networks:
        - app-network
    restart: always

networks:
  app-network:
    driver: bridge



