version: '3.4'

services:
  conferenceattendees.api:
    image: ${DOCKER_REGISTRY-}conferenceattendeesapi
    build:
      context: .
      dockerfile: ConferenceAttendees.Api/Dockerfile
    ports:
       - "7106:7106"
    depends_on: [mssql,seq_logs]
    networks:
        - app-network

  mssql:
    image: "pysachindocker/conferenceattendeedb"
    container_name: sql2
    hostname: mssql    
    environment: 
      - MSSQL_DATA_DIR=/var/opt/sqlserver/data
      - MSSQL_LOG_DIR=/var/opt/sqlserver/log
      - MSSQL_BACKUP_DIR=/var/opt/sqlserver/backup
    restart: unless-stopped
    ports:
        - "1401:1433"
    volumes: 
          - sqlsystem:/var/opt/mssql/
          - sqldata:/var/opt/sqlserver/data
          - sqllog:/var/opt/sqlserver/log
          - sqlbackup:/var/opt/sqlserver/backup
    networks:
        - app-network

  seq_logs:
    image: datalust/seq
    restart: unless-stopped
    ports:
        - "5342:80"
    environment:
        - ACCEPT_EULA=Y
    networks:
        - app-network
  nginx:
    build:
        context: .\nginx
        dockerfile: Dockerfile
    ports:
        - "8083:8083"
    depends_on:
        - conferenceattendees.api
    networks:
        - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:

